### PR TITLE
Add Post model to the admin UI

### PR DESCRIPTION
**Pull request by RootenberG**

### CODE REVIEW

**Comment by webknjaz** [comment]
> Registration

It's a process, not an action. You need an action there.

**Comment by RootenberG** [comment]
> > Registration
> 
> It's a process, not an action. You need an action there.

Of course, sorry.

**Comment by webknjaz** [comment]
> Register of the Post model

реєстр моделі поста?

**Comment by RootenberG** [comment]
> > Register of the Post model
> 
> реєстр моделі поста?


Registered Post Model?

**Comment by webknjaz** [comment]
`Add Post model to the admin UI`

**Comment by webknjaz** [comment]
don't forget to adjust PRs too

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
